name: On Template
on:
    push:
        branches:
            - master
            - main
jobs:
    template-replace:
        name: On template
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - run: npm ci
            - name: Replace
              run: node ./on-template.js
            - name: Commit changes
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add -A
                  git diff --staged --quiet || git commit -m "chore: replace template variables"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
